### ISSUE TITLE
Clean security groups and floating IPs

### ISSUE THREAD

**Issue by enolfc** [EGI-Federation/fedcloud-vm-monitoring#21]
# Short Description of the issue

Security groups and floating IPs get created and managed independently of VMs which may imply that they exist beyond its usage by some VMs. We should check that existing security groups and IPs allocated are actually used at some VM and remove them if that's not the case (we may have some grace period if needed)

# Summary of proposed changes

**Comment by sebastian-luna-valero** [comment]
After https://github.com/EGI-Federation/fedcloud-vm-monitoring/pull/24 should we close this?
